services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactdomrender
      MONGO_INITDB_ROOT_PASSWORD: qwerty123
    ports:
      - 27017:27017

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    depends_on:
      - elasticsearch
    image: kibana:${STACK_VERSION}
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
    - ${KIBANA_PORT}:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  app-neo4j:
    image: neo4j:latest
    container_name: app-neo4j_container
    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/conf/:/conf/'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    networks:
      - neo4j_go_net
    command: neo4j

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  redis_data:
  mongo-data-volume:

networks:
  neo4j_go_net:
    driver: bridge
